module.exports = {
  reactStrictMode: true,
  images: {
    domains: [
      'https://www.cheapshark.com',
      'assets.https://www.cheapshark.com',
      'assets.www.cheapshark.com',
      'www.cheapshark.com',
      'assets.cheapshark.com',
      'cheapshark.com',
      'cdn.cloudflare.steamstatic.com',
      'gamersgatep.imgix.net',
      'hb.imgix.net',
      'images.greenmangaming.com',
      'www.wingamestore.com',
      'static.voidu.com',
      'store.ubi.com',
      'cdn.static.nexway.com',
      'images.2game.com',
      'www.indiegalacdn.com',
      'cdn.fanatical.com',
      'images-4.gog-statics.com',
    ],
  },
}
